# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x07imagepb\"`\n\x0eProcessRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12%\n\toperation\x18\x03 \x01(\x0e\x32\x12.imagepb.Operation\"Y\n\x0fProcessResponse\x12\x13\n\x0boutput_path\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nsize_bytes\x18\x04 \x01(\x03*R\n\tOperation\x12\x19\n\x15OPERATION_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x43OMPRESS\x10\x01\x12\r\n\tTHUMBNAIL\x10\x02\x12\r\n\tWATERMARK\x10\x03\x32Q\n\x0cImageService\x12\x41\n\x0cProcessImage\x12\x17.imagepb.ProcessRequest\x1a\x18.imagepb.ProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=213
  _globals['_OPERATION']._serialized_end=295
  _globals['_PROCESSREQUEST']._serialized_start=24
  _globals['_PROCESSREQUEST']._serialized_end=120
  _globals['_PROCESSRESPONSE']._serialized_start=122
  _globals['_PROCESSRESPONSE']._serialized_end=211
  _globals['_IMAGESERVICE']._serialized_start=297
  _globals['_IMAGESERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
